name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - name: npm publish
        run: |
          GIT_TAG="${GITHUB_REF_NAME}"

          if [[ "$GIT_TAG" == *-* ]]; then
            NPM_TAG="${GIT_TAG#*-}"
            echo "prerelease tag detected: publishing with npm dist-tag '$NPM_TAG'"
            npm publish --tag "$NPM_TAG"
          else
            echo "stable tag detected: publishing with default npm dist-tag"
            npm publish
          fi
